try {
	const number = 20;
	console.log(numbers);
} catch (error) {
	console.log("errors");
}
